name: Update Cakhia M3U

on:
  schedule:
    - cron: '*/30 * * * *' # Chạy mỗi 30 phút
  workflow_dispatch: # Cho phép bấm chạy tay

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install curl_cffi beautifulsoup4

      - name: Run scraper
        run: python cakhia_scraper.py

      - name: Commit and push
        run: |
          git config --global user.name "Github Action"
          git config --global user.email "action@github.com"
          git add cakhia_live.m3u
          git commit -m "Update playlist $(date)" || exit 0
          git push
          
